/*
 * generated by Xtext 2.23.0
 */
package fr.ensma.idm.choreography.robottxtsyntax.parser.antlr;

import com.google.inject.Inject;
import fr.ensma.idm.choreography.robottxtsyntax.parser.antlr.internal.InternalTxtDslParser;
import fr.ensma.idm.choreography.robottxtsyntax.services.TxtDslGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class TxtDslParser extends AbstractAntlrParser {

	@Inject
	private TxtDslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalTxtDslParser createParser(XtextTokenStream stream) {
		return new InternalTxtDslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Choreography";
	}

	public TxtDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(TxtDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
