/*
 * generated by Xtext 2.23.0
 */
package fr.ensma.idm.choreography.robottxtsyntax.ide;


/**
 * Use this class to register ide components.
 */
public class TxtDslIdeModule extends AbstractTxtDslIdeModule {
}
