/*
 * generated by Xtext 2.23.0
 */
package fr.ensma.idm.choreography.robottxtsyntax.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import fr.ensma.idm.choreography.robottxtsyntax.TxtDslRuntimeModule;
import fr.ensma.idm.choreography.robottxtsyntax.TxtDslStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class TxtDslIdeSetup extends TxtDslStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new TxtDslRuntimeModule(), new TxtDslIdeModule()));
	}
	
}
