/*
 * generated by Xtext 2.23.0
 */
package fr.ensma.idm.choreography.robottxtsyntax;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class TxtDslStandaloneSetup extends TxtDslStandaloneSetupGenerated {

	public static void doSetup() {
		new TxtDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
