/*
 * generated by Xtext 2.23.0
 */
package fr.ensma.idm.choreography.robottxtsyntax;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class TxtDslRuntimeModule extends AbstractTxtDslRuntimeModule {
}
