/*
 * generated by Xtext 2.23.0
 */
package fr.ensma.idm.choreography.robottxtsyntax.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class TxtDslUiModule extends AbstractTxtDslUiModule {

	public TxtDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
