/*
 * generated by Xtext 2.23.0
 */
package fr.ensma.idm.choreography.robottxtsyntax.ui;

import com.google.inject.Injector;
import fr.ensma.idm.choreography.robottxtsyntax.ui.internal.RobottxtsyntaxActivator;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class TxtDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(RobottxtsyntaxActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		RobottxtsyntaxActivator activator = RobottxtsyntaxActivator.getInstance();
		return activator != null ? activator.getInjector(RobottxtsyntaxActivator.FR_ENSMA_IDM_CHOREOGRAPHY_ROBOTTXTSYNTAX_TXTDSL) : null;
	}

}
